### ISSUE TITLE
IPv4-mask  for notrack

### ISSUE THREAD

**Issue by tackin** [freifunktrier/Supernodes#1]
Hi @Ranlvor !
# disable conntrack für everything exept 10.172.0.8 - 10.172.0.16

echo "
...
-A notrack-helper-PREROUTING -s 10.172.0.8/29 -j RETURN

Wirf mal einen Blick da drauf. 
Die Netmask geht von 10.172.0.8 - 10.172.0.14
10.172.0.15 ist schon Bradcast und .16 liegt aber wohl doch definitiv draußen.
Oder?

Gruß
tackin
(/me ist nicht sicher ob du bei nem issue wie dem hier selbst auch ne Mail/info bekommst.)

**Comment by Ranlvor** [comment]
Du hast Recht. 16 ist draußen. 15 ist aber noch drin, da Brodcast/Netzadresse/Hostadresse an der Stelle egal ist, da ich keine Route habe sondern nur Adressen auswähle, auf denen iptables sich anders verhalten soll.
